services:
  postgres:
    image: postgres:16
    container_name: postgres-iam
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-iam:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  stalwart:
    image: stalwartlabs/stalwart:latest
    container_name: stalwart
    ports:
      - "8080:8080"
      - "25:25"
      - "143:143"
      - "587:587"
    volumes:
      - stalwart_data:/opt/stalwart
    restart: unless-stopped
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "3001:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=stalwart
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=stalwart
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
    depends_on:
      - stalwart
    restart: unless-stopped

volumes:
  postgres_data:
  stalwart_data:
